### ISSUE TITLE
read only access manager account 

### ISSUE THREAD

**Issue by karnanishikha** [anujtenani/goaffpro#178] opened 2021-06-09 11:15 UTC
I would like to know if the Goaffpro app has a feature of "read-only" access for an administrator to the back end of sub-affiliates' portals? For example. I need to grant the access to one of our partners. So can I just grant the "read-only" access

**Comment by anujtenani** [comment] 2021-08-21 18:59
Duplicate of #205

**Closed by anujtenani** 2021-08-21 18:59 UTC
